version: "2"

checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
      
plugins:
  phpcodesniffer:
    enabled: true
    config:
      standard: psr2

  phpmd:
    enabled: true
    config:
      rulesets: phpmd.xml
