tools:
  external_code_coverage:
    enabled: true

  php_analyzer:
    enabled: true
    filter:
      paths:
        - src/**/*.php

  php_changetracking:
    enabled: true

  php_code_coverage:
    enabled: true

  php_code_sniffer:
    enabled: true
    config:
      standard: psr2

  php_cpd:
    enabled: true

  php_cs_fixer:
    enabled: true
    config:
      level: psr2

  php_hhvm:
    enabled: true

  php_loc:
    enabled: true

  php_mess_detector:
    enabled: true
  
  php_pdepend:
    enabled: true

  sensiolabs_security_checker:
    enabled: true
