sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false

env:
  global:
    - setup=stable
    - CC_TEST_REPORTER_ID=605de681587e09b4c68c829c04048e9302642c5aa5b1e55e4a45089bbc59108d

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: 7.3
    - php: 7.3
      env: setup=lowest

before_install:
  - travis_retry composer self-update

install:
  - |
    if [[ "$setup" == "stable" ]]; then
      travis_retry composer update --prefer-dist --no-scripts --no-interaction --prefer-stable --no-suggest;
    fi
    if [[ "$setup" == "lowest" ]]; then
      travis_retry composer update --prefer-dist --no-scripts --no-interaction --prefer-lowest --prefer-stable --no-suggest;
    fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mkdir -p build/logs
  - composer test

after_success:
  - travis_retry composer require --dev php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls -v
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
