<?php

namespace Cknow\Money;

/**
 * Money.
 *
 * @method static Money AED(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ALL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money AMD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ANG(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money AOA(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ARS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money AUD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money AWG(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money AZN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BAM(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BBD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BDT(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BGN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BHD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BIF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BMD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BND(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BOB(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BOV(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BRL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BSD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BTN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BWP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BYN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money BZD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CAD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CDF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CHE(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CHF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CHW(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CLF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CLP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CNY(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money COP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money COU(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CRC(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CUC(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CUP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CVE(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money CZK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money DJF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money DKK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money DOP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money DZD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money EGP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ERN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ETB(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money EUR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money FJD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money FKP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GBP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GEL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GHS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GIP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GMD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GNF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GTQ(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money GYD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money HKD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money HNL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money HRK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money HTG(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money HUF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money IDR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ILS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money INR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money IQD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money IRR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ISK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money JMD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money JOD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money JPY(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KES(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KGS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KHR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KMF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KPW(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KRW(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KWD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KYD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money KZT(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money LAK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money LBP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money LKR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money LRD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money LSL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money LYD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MAD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MDL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MGA(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MKD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MMK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MNT(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MOP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MRU(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MUR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MVR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MWK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MXN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MXV(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MYR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money MZN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money NAD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money NGN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money NIO(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money NOK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money NPR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money NZD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money OMR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PAB(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PEN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PGK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PHP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PKR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PLN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money PYG(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money QAR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money RON(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money RSD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money RUB(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money RWF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SAR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SBD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SCR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SDG(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SEK(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SGD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SHP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SLL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SOS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SRD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SSP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money STN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SVC(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SYP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money SZL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money THB(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TJS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TMT(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TND(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TOP(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TRY(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TTD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TWD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money TZS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money UAH(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money UGX(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money USD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money USN(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money UYI(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money UYU(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money UYW(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money UZS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money VES(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money VND(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money VUV(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money WST(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XAF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XAG(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XAU(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XBA(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XBB(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XBC(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XBD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XBT(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XCD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XDR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XOF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XPD(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XPF(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XPT(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XSU(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XTS(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XUA(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money XXX(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money YER(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ZAR(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ZMW(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 * @method static Money ZWL(mixed $amount, string|null $locale, \Money\Currencies|null $currencies)
 */
trait MoneyFactory
{
    /**
     * __callStatic.
     *
     * @param  string  $method
     * @param  array  $arguments
     * @return \Cknow\Money\Money
     */
    public static function __callStatic($method, array $arguments)
    {
        return new Money(
            $arguments[0],
            Money::parseCurrency($method),
            $arguments[1] ?? null,
            $arguments[2] ?? null
        );
    }

    /**
     * Create a new instance from the base money instance.
     *
     * @param  \Money\Money  $instance
     * @return \Cknow\Money\Money
     */
    public static function fromMoney(\Money\Money $instance)
    {
        return new Money($instance->getAmount(), $instance->getCurrency());
    }
}
